<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="coverlet.collector" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" />
		<PackageReference Include="xunit.runner.visualstudio">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="xunit.v3" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="Xunit" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="TestCases\BitwiseOperators\" />
		<Folder Include="TestCases\BitwiseCompound\" />
		<Folder Include="TestCases\Flow\" />
		<Folder Include="TestCases\Collections\" />
		<Folder Include="TestCases\Memory\" />
		<Folder Include="TestCases\Modular\App\" />
		<Folder Include="TestCases\Generics\" />
		<Folder Include="TestCases\Modular\StringComparison\" />
		<Folder Include="TestCases\Objects\" />
		<Folder Include="TestCases\ShiftOperators\" />
		<!-- Force MSBuild to include and copy all loose test assets recursively -->
		<None Include="TestCases\**\*" CopyToOutputDirectory="PreserveNewest" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Cvolo.Analysis\Cvolo.Analysis.csproj" />
		<ProjectReference Include="..\Cvolo.Core\Cvolo.Core.csproj" />
		<ProjectReference Include="..\Cvolo.Emitter.LLVM\Cvolo.Emitter.LLVM.csproj" />
		<ProjectReference Include="..\Cvolo.Syntax\Cvolo.Syntax.csproj" />
		<ProjectReference Include="..\Cvolo\Cvolo.csproj" />
	</ItemGroup>
</Project>