<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<RootNamespace>Cvolo.Projects</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Cvolo.Core\Cvolo.Core.csproj" />
		<ProjectReference Include="..\Cvolo.Syntax\Cvolo.Syntax.csproj" />
		<ProjectReference Include="..\Cvolo.Syntax.Antlr\Cvolo.Syntax.Antlr.csproj" />
		<ProjectReference Include="..\Cvolo.Analysis\Cvolo.Analysis.csproj" />
		<ProjectReference Include="..\Cvolo.Packaging\Cvolo.Packaging.csproj" />
	</ItemGroup>

</Project>
