<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Antlr4.Runtime.Standard" />
		<PackageReference Include="libLLVM.runtime.win-x64" />
		<PackageReference Include="LLVMSharp" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" />
		<PackageReference Include="System.CommandLine" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Cvolo.Core\Cvolo.Core.csproj" />
		<ProjectReference Include="..\Cvolo.Syntax\Cvolo.Syntax.csproj" />
		<ProjectReference Include="..\Cvolo.Analysis\Cvolo.Analysis.csproj" />
		<ProjectReference Include="..\Cvolo.Emitter.LLVM\Cvolo.Emitter.LLVM.csproj" />
	</ItemGroup>

	<!-- Windows x64 Tooling (Only copied when building for Windows) -->
	<ItemGroup Condition=" '$(RuntimeIdentifier)' == 'win-x64' Or '$(RuntimeIdentifier)' == '' ">
		<None Include="tooling\win-x64\clang.exe" CopyToOutputDirectory="PreserveNewest" Link="clang.exe" Visible="False" />
		<None Include="tooling\win-x64\lld-link.exe" CopyToOutputDirectory="PreserveNewest" Link="lld-link.exe" Visible="False" />
	</ItemGroup>
	
	<!-- Linux x64 Tooling (Only copied when building for Linux) -->
	<ItemGroup Condition=" '$(RuntimeIdentifier)' == 'linux-x64' ">
		<None Include="tooling\linux-x64\clang" CopyToOutputDirectory="PreserveNewest" Link="clang" Visible="False" />
	</ItemGroup>

</Project>
