namespace Cvolo.Core.AST.Base;

public enum SyntaxKind
{
	CompilationUnit,
	FunctionDeclaration,
	ExternDeclaration,
	Parameter,
	BlockStatement,
	ReturnStatement,
	ExpressionStatement,
	CallExpression,
	StringLiteralExpression,
	CharLiteralExpression,
	IntegerLiteralExpression,
	IdentifierExpression,
	VariableDeclaration,
	VariableAssignment,
	BinaryExpression,
	UnaryExpression,
	IfStatement,
	WhileStatement,
	ForStatement,
	StructDeclaration,
	DoubleLiteralExpression,
	BooleanLiteralExpression,
	MemberAccessExpression,
	StructInitializationExpression,
	BorrowExpression,
	HeapAllocationExpression,
	IndexExpression,
	ArrayInitializationExpression,
	TernaryExpression,
	UsingDirective,
	NamespaceDeclaration,
}
