lexer grammar CvoloLexer;

channels { COMMENTS }

// Keywords
VAL: 'val';
VAR: 'var';
REFVAR: 'refvar';
HEAP: 'heap';
REF: 'ref';
EXTERN: 'extern';
RETURN: 'return';
IF: 'if';
ELSE: 'else';
WHILE: 'while';
FOR: 'for';
TRUE: 'true';
FALSE: 'false';
NULL: 'null';
VOID: 'void';
INT: 'int';
UINT: 'uint';
LONG: 'long';
ULONG: 'ulong';
SHORT: 'short';
USHORT: 'ushort';
BYTE: 'byte';
SBYTE: 'sbyte';
DOUBLE: 'double';
FLOAT: 'float';
NINT: 'nint';
NUINT: 'nuint';
BOOL: 'bool';
STRING: 'string';
CHAR: 'char';
STRUCT: 'struct';
UNION: 'union';
ENUM: 'enum';
PRIVATE: 'private';
INTERNAL: 'internal';
PUBLIC: 'public';
UNSAFE: 'unsafe';
UNBOUND: 'unbound';
PANIC: 'panic';
EXTENSION: 'extension';
INTERFACE: 'interface';
PROTOCOL: 'protocol';
EMBED: 'embed';
NAMESPACE: 'namespace';
USING: 'using';
EXPOSE: 'expose';
GLOBAL: 'global';
SWITCH: 'switch';
CASE: 'case';
DEFAULT: 'default';
WHERE: 'where';
IS: 'is';
ALIAS: 'alias';
DEFER: 'defer';
ASM: 'asm';
VOLATILE: 'volatile';
ALIGNSTACK: 'alignstack';
INTEL: 'intel';
NAMEOF: 'nameof';
TYPEOF: 'typeof';
BREAK: 'break';
CONTINUE: 'continue';

// Punctuation
LPAREN: '(';
RPAREN: ')';
LBRACE: '{';
RBRACE: '}';
LBRACK: '[';
RBRACK: ']';
SEMI: ';';
COMMA: ',';
DOT: '.';
COLON: ':';
QMARK: '?';

// Operators
PLUS: '+';
MINUS: '-';
STAR: '*';
DIV: '/';
PERCENT: '%';
AMPERSAND: '&';
PIPE: '|';
CARET: '^';
TILDE: '~';
EXCLAMATION: '!';
ASSIGN: '=';
LT: '<';
GT: '>';
EQ: '==';
NEQ: '!=';
LTE: '<=';
GTE: '>=';
AND: '&&';
OR: '||';
PLUS_ASSIGN: '+=';
MINUS_ASSIGN: '-=';
STAR_ASSIGN: '*=';
DIV_ASSIGN: '/=';
ARROW: '->';
ELLIPSIS: '...';
INC: '++';
DEC: '--';
LSHIFT: '<<';
LSHIFT_ASSIGN: '<<=';
RSHIFT_ASSIGN: '>>=';
URSHIFT_ASSIGN: '>>>=';
AND_ASSIGN: '&=';
OR_ASSIGN: '|=';
XOR_ASSIGN: '^=';

// Literals
CharLiteral: '\'' (EscapeSequence | ~['\\\r\n]) '\'';
BadEmptyCharLiteral: '\'' '\'';
BadCharLiteral: '\'' (~['\r\n])+ '\'';
fragment RawStringBody: (~["] | '""')*;
RawStringLiteral: '@"' RawStringBody '"';
InterpolatedRawStringLiteral: ('@$"' | '$@"') RawStringBody '"';
BadRawStringLiteral: '@"' RawStringBody [\r\n];
BadInterpolatedRawStringLiteral: ('@$"' | '$@"') RawStringBody [\r\n];
InterpolatedStringLiteral: '$"' (EscapeSequence | ~["\\\r\n])* '"';
StringLiteral: '"' (EscapeSequence | ~["\\\r\n])* '"';
fragment EscapeSequence: '\\' [0nrt'"\\] | '\\' 'x' HexDigit+;
fragment Digit: [0-9];
fragment HexDigit: [0-9a-fA-F];
fragment BinaryDigit: [01];
fragment Digits: Digit ('_'* Digit)*;
fragment IntegerSuffix: [uU] [lL]? | [lL] [uU]?;
IntegerLiteral: '0' [xX] HexDigit ('_'* HexDigit)* IntegerSuffix? | '0' [bB] BinaryDigit ('_'* BinaryDigit)* IntegerSuffix? | Digits IntegerSuffix?;
BadLeadingUnderscoreNumber: '_' Digit+;
DoubleLiteral: Digits '.' Digits ExponentPart? FloatSuffix? | Digits ExponentPart FloatSuffix? | Digits FloatSuffix;
fragment ExponentPart: [eE] [+-]? Digit+;
fragment FloatSuffix: [fFdD];
TrailingUnderInteger: Digits '_';
BadIntegerSuffix: ('0' [xX] HexDigit ('_'* HexDigit)* | '0' [bB] BinaryDigit ('_'* BinaryDigit)* | Digits IntegerSuffix?) [a-zA-Z]+;
BadDoubleLiteral: (Digits '.' Digits ExponentPart? | Digits ExponentPart) [a-zA-Z];
Identifier: [a-zA-Z_][a-zA-Z0-9_]*;

// Whitespace and comments
WS: [ \t\r\n]+ -> skip;
LineComment: '//' ~[\r\n]* -> channel(COMMENTS);
BlockComment: '/*' .*? '*/' -> channel(COMMENTS);
