<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<RootNamespace>Cvolo.Compiler.Tooling</RootNamespace>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Cvolo.Core\Cvolo.Core.csproj" />
		<ProjectReference Include="..\Cvolo.Syntax\Cvolo.Syntax.csproj" />
		<ProjectReference Include="..\Cvolo.Syntax.Antlr\Cvolo.Syntax.Antlr.csproj" />
		<ProjectReference Include="..\Cvolo.Analysis\Cvolo.Analysis.csproj" />
		<PackageReference Include="Antlr4.Runtime.Standard" />
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="Cvolo.Tests.Tooling" />
	</ItemGroup>

	<Import Project="Tooling.Artifact.targets" />

</Project>
