<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>
	
	<ItemGroup>
		<PackageReference Include="LLVMSharp" />
		<PackageReference Include="libLLVM.runtime.linux-x64" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Cvolo.Core\Cvolo.Core.csproj" />
		<ProjectReference Include="..\Cvolo.Analysis\Cvolo.Analysis.csproj" />
	</ItemGroup>

</Project>
